### ISSUE TITLE
How do I copy your slide format?

### ISSUE THREAD

**Issue by sje30** [benmarwick/UW-eScience-reproducibility-social-sciences#1]
hi Ben,

what format are your slides in?  Is the .Rpres format something specific to e.g. rstudio?  I need to make a new slide deck and was thinking of trying a style like you used here in Cam last December.  I like the "ioslides" format, but I did think your slides looked neater!

**Comment by benmarwick** [comment]
Yes, the Rpres format is built into RStudio. It's like a minor local variation of the Rmd slide formats, but Rpres allows for columns on slides and in-pane previews while editing, which make things a tiny bit easier.

The main documentation (which is not extensive) seems to be here: https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations 

I also use a bit of HTML in my Rpres files to make things look more like what I want.

**Comment by sje30** [comment]
Ok, thanks Ben.  Have just asked Rstudio team if the slides can be generated outside of Rstudio.

**Comment by benmarwick** [comment]
Good idea, I'd be interested to know if that is possible

**Comment by sje30** [comment]
No solution from the rstudio team... got a rather unhelpful reply
pointing me to knitr!

**Comment by benmarwick** [comment]
That's disappointing, makes it seem like not one of their proudest features in the IDE, perhaps it'll be phased out...
